image: maven:3.6.3-openjdk-15

stages:
    - build

maven-build:
    stage: build
    script: "mvn package"
    artifacts:
        paths:
            - target/surefire-reports/TEST-*.xml
        reports:
            junit:
                - target/surefire-reports/TEST-*.xml
