image: maven:3.6.3-openjdk-14

stages:
    - build

maven-build:
    stage: build
    script: "mvn package"
    artifacts:
        reports:
            junit:
                - target/surefire-reports/TEST-*.xml
